### ISSUE TITLE
How to reinit height?

### ISSUE THREAD

**Issue by Venegrad** [BrentonCozby/dom-slider#16]
If ill use slideDown, and after inside element change height (like add some items in spoiler), after slideUp and slideDOwn will bug, because start animation from old height.

**Comment by BrentonCozby** [comment]
@Venegrad the library was caching the height, but I saw no good reason to do this since the height is calculated every time a slide is triggered. Therefore, I removed the cached height so it now uses the latest height every time. I've also updated the example to include dynamic heights. Thanks for reporting this issue. You can download the fixed library with [v2.2.0](https://github.com/BrentonCozby/dom-slider/releases/tag/2.2.0).
